// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/6/2025, 12:00:32 AM
const configMerger = require("C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nitro/Desktop/Winter/AI Clothing/frontend/app.config.{js,ts,mjs}"] } }));

module.exports = config
